dep.minecraft=26.1.2
meta.minecraft-range=[26.1,26.2)

dep.fapi=0.145.4+26.1.2
meta.fapi-range=[0.144.3,)

dep.neoforge=26.1.2.84
dep.klf=2.14.1-k2.4.20-3.1+neoforge

dep.yacl=3.9.7+26.1-fabric
dep.yacl-neoforge=3.9.7+26.1-neoforge
meta.yacl-range=[,)

dep.mod-menu=18.0.0

dep.controlify=3.5.3+mc26.1
